export enum SettingMenuItemsPages {
  Wallet = 'wallet',
  WelcomePoints = 'WELCOME_POINTS',
  GovernmentAgencies = 'Government_Agencies',
  VisitsReport = 'visits_report',
  PrescriptionList = 'prescription_list',
  Favorites = 'favorites',
  WalletGift = 'wallet-gift',
  ReferralCode = 'REFERRAL_CODE',
  Security = 'security',
  FAQs = 'FAQs',
  Problems = 'Problems',
  ImportantNumbers = 'ImportantNumbers',
  ContactUs = 'ContactUs',
  RateApp = 'RateApp',
  InviteFriends = 'InviteFriends',
  TechnicalSupport = 'Technical_Support',
}
