import { ALL_INPUT_TYPES, IFormInputConfig, InputIconPosition, InputIconType } from "../../../shared";
import { Validators } from "@angular/forms";

export const PatientDetailsConfig: IFormInputConfig[] = [
  {
    id: 'patientDetailsName',
    type: ALL_INPUT_TYPES.TEXT,
    name: 'name',
    label: 'full_name',
    isRequired: true,
    placeholder: 'full_name_placeholder',
    defaultValue: null,
    isDisabled: false,
    widthClass: 'w-full',
    inputWithIcon: false,
    inputIconType: InputIconType.IMAGE,
    inputIcon: 'images/icons/profile.svg',
    inputIconPosition: InputIconPosition.START,
    globalClass: 'custom-input-wrapper',
    inputClass: 'form-control',
    validation: [
      { function: Validators.required, errorMessage: 'full_name_required' },
      { function: Validators.pattern(/^[A-Za-z\s]+$/), errorMessage: 'full_name_pattern', errorName: 'pattern' }
    ],
    enableLabelClick: true,
    stopPaste: true,
  },
  {
    id: 'patientDetailsGender',
    type: ALL_INPUT_TYPES.SELECT,
    inputWithIcon: false,
    inputIconType: InputIconType.IMAGE,
    inputIcon: 'images/icons/password.svg',
    inputIconPosition: InputIconPosition.START,
    listValues: [
      { value: 'male', label: 'male' },
      { value: 'female', label: 'female' }
    ],
    optionLabel: 'label',
    optionValue: 'value',
    name: 'gender',
    label: 'gender',
    placeholder: 'choose_gender',
    isRequired: true,
    defaultValue: null,
    isDisabled: false,
    widthClass: 'w-half',
    validation: [
      { function: Validators.required, errorMessage: 'gender_required' }
    ],
    enableLabelClick: true
  },
  {
    id: 'patientDetailsAge',
    type: ALL_INPUT_TYPES.NUMBER,
    name: 'age',
    label: 'age',
    isRequired: true,
    placeholder: 'age_placeholder',
    defaultValue: null,
    isDisabled: false,
    widthClass: 'w-half',
    inputWithIcon: false,
    inputIconType: InputIconType.IMAGE,
    inputIcon: 'images/icons/email.svg',
    inputIconPosition: InputIconPosition.START,
    globalClass: 'custom-input-wrapper',
    inputClass: 'form-control',
    validation: [
      { function: Validators.required, errorMessage: 'age_required' }
    ],
    enableLabelClick: true,
    stopPaste: true,
  },
  {
    id: 'patientDetailsProblem',
    type: ALL_INPUT_TYPES.TEXTAREA,
    name: 'problem',
    label: 'problem',
    isRequired: false,
    placeholder: 'problem_placeholder',
    defaultValue: null,
    isDisabled: false,
    widthClass: 'w-full',
    inputWithIcon: false,
    inputIconType: InputIconType.IMAGE,
    inputIcon: 'images/icons/profile.svg',
    inputIconPosition: InputIconPosition.START,
    globalClass: 'custom-input-wrapper',
    inputClass: 'form-control',
    validation: [
      { function: Validators.required, errorMessage: 'problem_required' },
      // { function: Validators.pattern(/^[A-Za-z\s]+$/), errorMessage: 'form.problem.errors.pattern', errorName: 'pattern' }
    ],
    enableLabelClick: true,
    stopPaste: true,
  },

  // {
  //   id: 'patientDetailsEmail',
  //   type: ALL_INPUT_TYPES.EMAIL,
  //   name: 'email',
  //   label: 'form.email.label',
  //   isRequired: true,
  //   placeholder: 'form.email.placeholder',
  //   defaultValue: null,
  //   isDisabled: false,
  //   widthClass: 'w-half',
  //   inputWithIcon: false,
  //   inputIconType: InputIconType.IMAGE,
  //   inputIcon: 'images/icons/email.svg',
  //   inputIconPosition: InputIconPosition.START,
  //   globalClass: 'custom-input-wrapper',
  //   inputClass: 'form-control',
  //   validation: [
  //     { function: Validators.required, errorMessage: 'form.email.errors.required' },
  //     { function: Validators.email, errorMessage: 'form.email.errors.email', errorName: 'email' }
  //   ],
  //   enableLabelClick: true,
  //   stopPaste: true,
  // },
  // {
  //   id: 'patientDetailsIdentifyNumber',
  //   type: ALL_INPUT_TYPES.TEXT,
  //   name: 'identifyNumber',
  //   label: 'form.IdentifyNumber.label',
  //   isRequired: true,
  //   placeholder: 'form.IdentifyNumber.placeholder',
  //   defaultValue: null,
  //   isDisabled: false,
  //   widthClass: 'w-half',
  //   inputWithIcon: false,
  //   inputIconType: InputIconType.IMAGE,
  //   inputIcon: 'images/icons/email.svg',
  //   inputIconPosition: InputIconPosition.START,
  //   globalClass: 'custom-input-wrapper',
  //   inputClass: 'form-control',
  //   validation: [
  //     { function: Validators.required, errorMessage: 'form.IdentifyNumber.errors.required' }
  //   ],
  //   enableLabelClick: true,
  //   stopPaste: true,
  // },
  // {
  //   id: 'registerPhoneCode',
  //   type: ALL_INPUT_TYPES.COUNTRYCODEINPUT,
  //   name: 'phoneNumber',
  //   label: 'form.phoneCode.label',
  //   isRequired: true,
  //   placeholder: 'phone_placeholder',
  //   defaultValue: null,
  //   isDisabled: false,
  //   widthClass: 'w-half',
  //   inputWithIcon: false,
  //   inputIcon: 'images/icons/call.svg',
  //   inputIconType: InputIconType.IMAGE,
  //   inputIconPosition: InputIconPosition.START,
  //   globalClass: 'custom-input-wrapper',
  //   inputClass: 'form-control',
  //   validation: [
  //     { function: Validators.required, errorMessage: 'phone_required' },
  //     { function: Validators.pattern(/^[0-9]+$/), errorMessage: 'phone_pattern', errorName: 'pattern' },
  //     { function: Validators.minLength(3), errorMessage: 'phone_min_length', errorName: 'minlength' },
  //     { function: Validators.maxLength(12), errorMessage: 'phone_max_length', errorName: 'maxlength' }
  //   ],
  //   enableLabelClick: true,
  //   stopPaste: true
  // },
];
